// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsG9QITUFOZQ4epkUzSAT8kwgevYA6uE0',
    appId: '1:543656610577:web:0a7cfc4c0186cd93dd1ab0',
    messagingSenderId: '543656610577',
    projectId: 'pokeflutter-f8989',
    authDomain: 'pokeflutter-f8989.firebaseapp.com',
    storageBucket: 'pokeflutter-f8989.firebasestorage.app',
    measurementId: 'G-9WN6B3NH1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFCYGnPRlQkHrfRCLq61mjXznbuOBHWQ',
    appId: '1:543656610577:android:ec83eae3599e4df5dd1ab0',
    messagingSenderId: '543656610577',
    projectId: 'pokeflutter-f8989',
    storageBucket: 'pokeflutter-f8989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGvF7i7osmYstxg785bjU7Kgkpxz_MJ8Q',
    appId: '1:543656610577:ios:c2af4c5e9619e5a0dd1ab0',
    messagingSenderId: '543656610577',
    projectId: 'pokeflutter-f8989',
    storageBucket: 'pokeflutter-f8989.firebasestorage.app',
    iosBundleId: 'com.example.pokeflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGvF7i7osmYstxg785bjU7Kgkpxz_MJ8Q',
    appId: '1:543656610577:ios:c2af4c5e9619e5a0dd1ab0',
    messagingSenderId: '543656610577',
    projectId: 'pokeflutter-f8989',
    storageBucket: 'pokeflutter-f8989.firebasestorage.app',
    iosBundleId: 'com.example.pokeflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsG9QITUFOZQ4epkUzSAT8kwgevYA6uE0',
    appId: '1:543656610577:web:a5015fb832d60fb6dd1ab0',
    messagingSenderId: '543656610577',
    projectId: 'pokeflutter-f8989',
    authDomain: 'pokeflutter-f8989.firebaseapp.com',
    storageBucket: 'pokeflutter-f8989.firebasestorage.app',
    measurementId: 'G-NLZPYQLS14',
  );
}
